# Generated by Django 5.1.6 on 2025-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica4app', '0003_alter_library_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
