# Generated by Django 5.1.6 on 2025-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica4app', '0004_alter_library_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
